fix: typeof bug when passing timeout to dag.get
Passing `options` without a `path` to dag.get will throw an error.
```
ipfs.dag.get(cidPath, { timeout: 2000 })

TypeError: Cannot read property 'timeout' of null
```

Cause by the lovely JS issue of `typeof null === 'object'`.

Co-authored-by: Kia Rahimian <kia@tintmail.com>